# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: super_registration_db
    restart: unless-stopped
    ports:
    - "5452:5432"
    environment:
      POSTGRES_DB: super_registration
      POSTGRES_USER: superreg
      POSTGRES_PASSWORD: house123